
var itemList = {
	intmod1 : [{
			header : "InterMaths",
			index: "chapter0",
			paragraph1: "InterMaths is a joint MSc programme leading to a double MSc degree in Applied and Interdisciplinary Mathematics between our 74 partners:",
			desc1: [{name: "University of L’Aquila in Italy (UAQ) [coordinating institution]",
						web: "https://www.intermaths.eu/partners/laquila",
					},
					{name: "Brno University of Technology in the Czech Republic (BUT)",
						web: "https://www.intermaths.eu/partners/brno",
					},
					{name: "University of Silesia in Katowice in Poland (US)",
						web: "https://www.intermaths.eu/partners/katowice",
					},	
					{name: "Ivan Franko National University of Lviv in Ukraine (IFNUL)",
						web: "https://www.intermaths.eu/partners/lviv",
					},
					{name: "V. N. Karazin Kharkiv National University in Ukraine (KhNU)",
						web: "https://www.intermaths.eu/partners/kharkiv",
					},
					{name: "Gdansk University of Technology in Poland (GUT)",
						web: "https://www.intermaths.eu/partners/gdansk",
					},
					{name: "Taras Shevchenko National University of Kyiv in Ukraine (TSNUK).",
						web: "https://www.intermaths.eu/partners/kyiv",
					},
				],
			paragraph2: "We offer an interdisciplinary mathematical education for both LOCAL and INTERNATIONAL students coming from all over the world. In a nutshell, studying in InterMaths means:",
			desc2: [{name: "2 different countries"},
					{name: "2 academic years (120 ECTS credits) structured in 4 semesters"},
					{name: "7 study paths"},
					{name: "programme entirely taught in English"},
					{name: "possibility to learn 2 European languages"},
					{name: "scholarships covering most tuition, accommodation and insurance expenses"},
				],
			
		},],
	intmod2 : [{
			header : "MathMods",
			index: "chapter1",
			paragraph1: "MathMods is a two-year (120 ECTS credits) Joint Master's Degree run by 4 European universities, which aim to provide students with a cross cultural education while they get acquainted with both theory and applications of mathematical modelling in engineering.",
			paragraph2: "Since its establishement in 2008 MathMods was funded by the EU Commission firstly through the Erasmus Mundus programme action 1 A (project no. 2008-0100), and later through the Erasmus+ Key Action 1 programme, project no. 2013-0227.",
			header1: "AIMS",
			paragraph3:"Mathematical modelling lies at the heart of most current technological innovations and has become a fundamental tool in many fields of engineering. Essentially multidisciplinary in its applications, mathematical modelling and simulation is in its own right a key technology which is bound to increase its presence within efficient industries and business innovation departments. The proposed programme reflects this multidisciplinarity, drawing on the unifying mathematical aspects from the various and often separate engineering disciplines. This allows the development of an essentially unified methodological approach to modelling and simulation of real engineering challenges",
			header2 : "CONSORTIUM",
			paragraph4: "The MathMods Consortium is coordinated by the University of L'Aquila in Italy (UAQ) and involves other four leading institutions in Europe:",
			desc1: [{name: "University of L'Aquila in Italy (UAQ) [Coordinating Institution]",
						web: "http://www.mathmods.eu/about/partners/l-aquila",
					},
					{name: "Vienna University of Technology in Austria (TUW)",
						web: "http://www.mathmods.eu/about/partners/vienna",
					},
					{name: "University of Hamburg (UHH) in Germany (UHH)",
						web: "http://www.mathmods.eu/about/partners/hamburg-uhh",
					},
					{name: "University of Côte d'Azur in Nice - France (UCA).",
						web: "http://www.mathmods.eu/about/partners/nice",
					},
				],
			paragraph5: "The geographical profile of the consortium covers South, Central and East Europe, bringing an air of diversity that contributes to the complementarity in the cultural aspects, in the teaching tradition, and in the expertise topics. The departments involved have a common topic in the key expression \"application of mathematics\", but from quite different perspectives. We believe that we have found in this partnership an interesting equilibrium between theory, computation, and application of the science and art of abstract modelling of real phenomena.",
			header3: "STUDY PROGRAMME, MOBILITY SCHEME AND STUDY PATHS",
			paragraph6: "The MathMods Master's degree course consists of a cycle of four semesters starting each September and awarding 30 ECTS credits each (thus 120 ECTS credits in total). The mobility scheme involves two different locations, at least, over the whole programme. The first year is common for all students: this is meant to provide for a homogeneous knowledge platform across the whole group. The second year is divided into five study paths (aka specialisations, branches or tracks), which reflect our partners' field of research and excellence. Students will eventually spend their fourth semester on preparing their Master's Thesis.",
			sem1: "Semester 1: Theory at UAQ, Italy",
			sem2: "Semester 2: Numerics at TUW (Austria) or UHH, Germany",
			sem3: "Semester 3: Applications at one of our 5 partners",
			sem4: "Semester 4: Thesis at UHH / UAQ / UCA / TUW",
			desc2: [{name: "Mathematical models in social sciences (UAQ, Italy)"},
					{name: "Mathematical modelling and optimisation (UAQ, Italy)"},
					{name: "Modelling and simulation of complex systems (UHH, Germany)"},
					{name: "Mathematical modelling applications to finance (UCA, France)"},
					{name: "Advanced modelling and numerics for applied PDEs (TUW, Austria)"},
				],
			aweb: "http://www.mathmods.eu",
			last: "Read more",
			
		},],
	displayImages: [
		{
			id : "image1",
			src: "images/img_1.jpg",
			alt: "unknown1",
			style: "display: none;",
		},
		{
			id : "image2",
			src: "images/img_2.jpg",
			alt: "unknown2",
			style: "display: none;",
		},
		{
			id : "image3",
			src: "images/img_3.jpg",
			alt: "unknown3",
			style: "display: none;",
		},
		{
			id : "image4",
			src: "images/img_4.jpg",
			alt: "unknown4",
			style: "display: none;",
		},
		{
			id : "image5",
			src: "images/img_5.jpg",
			alt: "unknown5",
			style: "display: none;",
		},
		{
			id : "image6",
			src: "images/img_6.jpg",
			alt: "unknown6",
			style: "display: none;",
		},
	],
	knowus : [
		{
			name : "Nigeria",
			index: "chapter0",
			description: "We are six Nigerians in this batch of Intermaths/Mathmods program.The journey started back then in Nigeria when we got the exciting news of the opportunity to leave the shores of our nation for a while. We rally round to get the required documents and gather funds for the journey. On getting here we were faced with other difficuties but we are overcoming.",
			imageIndex: "image1",
			src: "images/img_5.jpg",
			imageTitle: "Nigerian Students",
		},
		{
			name : "Ghana",
			index: "chapter1",
			description: "We are Ghanians and five of us are in this batch of Intermaths/Mathmods program.The journey started back then in Nigeria when we got the exciting news of the opportunity to leave the shores of our nation for a while. We rally round to get the required documents and gather funds for the journey. On getting here we were faced with other difficuties but we are overcoming.",
			imageIndex: "image2",
			src: "images/img_6.jpg",
			imageTitle: "Ghanian Students",
		},
		{
			name : "Others",
			index: "chapter2",
			description: "Apart from Nigerians and Ghanians that has a greater proportion of Africans, we come from Ethopia, Egypt, Uganda and other african countries. We joined this batch of Intermaths/Mathmods program around September 2018.The journey started back then in our countries when we got the exciting news of the opportunity to leave the shores of our nation for a while. We rally round to get the required documents and gather funds for the journey. On getting here we were faced with other difficuties but we are overcoming.",
			imageIndex: "image3",
			src: "images/img_4.jpg",
			imageTitle: "Other countries' Students",
		}
	]
};